### ISSUE TITLE
Move new use cases to github wiki

### ISSUE THREAD

**Issue by ghost** [moevm/nosql-2017-git_source_tree_search#3]
Move new use cases from:
https://docs.google.com/document/d/1eBXAk-gdrcPnK4eF6dJq6xuJU27UVvs4Iqf5LY5c1mU/edit
To:
https://github.com/moevm/nosql-2017-git_source_tree_search/wiki/%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82%D1%8B-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F

**Comment by ArtemPopof** [comment]
Done
