### ISSUE TITLE
Make example Python project for testing

### ISSUE THREAD

**Issue by ghost** [moevm/nosql-2017-git_source_tree_search#8]
Project must contain several (3-4) files;
Project structure should be like http://docs.python-guide.org/en/latest/writing/structure/;
Project must be tested by module unittest (don't place all tests in a single file) https://docs.python.org/3.6/library/unittest.html#module-unittest

Please close it till 07.01.2018.

**Comment by ghost** [comment]
@ArtemPopof add
https://github.com/ArtemPopof/GitSourceTreeSearchTest

**Comment by ArtemPopof** [comment]
Created some project, but it can contain some stupid mistakes becouse of my huge skills in Python. Link in closing message.
