### ISSUE TITLE
Написать Cypher-shell запросы для работы с Neo4j

### ISSUE THREAD

**Issue by ghost** [moevm/nosql-2017-git_source_tree_search#9]
Необходимо написать запросы на Cypher к Neo4j, для выполнения следующих операций:
> Functions that need to be implemented:
> - string addRepository(string pathToGit) -- create new repository with path == pathToGit, if not create  return ""
> - void removeRepository(string pathToGit) -- remove repository with path == pathToGit
> 
>Create "add" and "remove" functions to Commit, Test, Source same as to Repository.
>Use relative pathToCommit, pathToTest, pathToSource respectively.
>
>Create functions same as to Repository to add and remove relation "imports" from Test with path == pathToTest to Source with path == pathToSource:
>  - string addSourceToTest(string pathToSource, string pathToTest)
>  - void removeSourceFromTest(string pathToSource, string pathToTest)
> 
> Also need to be implemented:
> - string getPathToGit()
>   - return Repository::pathToGit
> - string getCurrentCommitHash(bool isAbbreviated)
>   - return fullHash of current Commit
>   - if isAbbreviated is true - return abbreviated commit hash
>   - default of isAbbreviated is false
> - vector[string] getCurrentCommitTests()
>   - return vector of Tests included to the Commit
>   - if the Commit doesn't have Tests included to it return empty vector
> - vector[string] getCurrentCommitSources()
>   - return vector of Sources included to the Commit
>   - if the Commit doesn't have Sources included to it return empty vector
> - vector[string] getTestSources(string pathToTest)
>   - return vector of Sources imported to the Test with path == pathToTest
>   - if the Test doesn't have Sources imported to it return empty vector
> - vector[string] getAllTests()
>   - return vector of all Tests in database
>   - if the database doesn't have Tests return empty vector
> - vector[string] getAllSources()
>   - return vector of all Sources in database
>   - if the database doesn't have Sources return empty vector
> - int getTestStatus(string pathToTest)
>   - return Test::status of Test with path == pathToTest 
> - int getSourceStatus(string pathToSource)
>   - return Source::status of Source with path == pathToSource

Реализация запросов необходима для обертывания в neo4j-driver (Python) и реализации логики прототипа. Структура БД описана в #4.

**Comment by JorgenPo** [comment]
Создал страницу с описанием основных запросов. Возможно, не все запросы пока описал, но основные запросы, вроде, есть.

https://github.com/moevm/nosql-2017-git_source_tree_search/wiki/%D0%97%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D1%8B-%D0%BA-%D0%B1%D0%B4

**Comment by ghost** [comment]
Дальнейшие запросы будут делаться по ходу дела. Задачу закрываю.
